### ISSUE TITLE
Build intermittently fails

### ISSUE THREAD

**Issue by alalonde** [TypeStrong/typedoc-default-themes#118]
I discovered this while rebasing my derived theme to the latest version from this repo. 

Occasionally `npm run build` will fail with an error such as 
```
Error: ENOENT: no such file or directory, open '<path>/typedoc-default-themes/bin/minimal/partials/toc.hbs'
```

I believe this is due to the `CleanWebpackPlugin()` ending up not being the first plugin, as recommended [here](https://github.com/johnagan/clean-webpack-plugin/issues/146#issuecomment-507862148).

**Comment by Gerrit0** [comment]
Resolved by #119, thanks!
