### ISSUE TITLE
How to change code color ?

### ISSUE THREAD

**Issue by Ayfri** [TypeStrong/typedoc-default-themes#125]
Hi!
I'm making a dark theme but I don't find the thing that set the color of the code and how to change it, can I get more information on this?

**Comment by Gerrit0** [comment]
https://github.com/TypeStrong/typedoc/issues/1473

**Comment by Ayfri** [comment]
Oh, so I have to wait for 0.21?

**Comment by Gerrit0** [comment]
I'd happily accept a PR for 0.20 that adds `--highlight-theme`, but if nobody submits a PR, then yeah, I probably won't get to it until 0.21.

**Comment by Gerrit0** [comment]
TypeDoc 0.20.20 contains a `--hightlightTheme` option
