### ISSUE TITLE
Make npm script run without errors on Windows

### ISSUE THREAD

**Issue by kamranayub** [TypeStrong/typedoc-default-themes#25]
The npm clean script will bomb on Windows machines which makes consumers have to handle errors when trying to build on CI or locally.

I plan to submit a PR to add a grunt clean task to replace the Unix commands to avoid any cross-platform errors.

**Comment by blakeembrey** [comment]
Are you using this directly? Anyone using from NPM shouldn't need the build or clean commands.

**Comment by kamranayub** [comment]
Yes, in order to use Typedoc it needs the default theme and because the CI services use a fresh copy of our repository and because we are referencing our fork of this repository as a submodule (since we had to make some enhancements that aren't in here), we have to run `npm install` which in turn triggers the npm `prepublish` script which in turn runs the clean and build commands.

See:

https://github.com/excaliburjs/typedoc-default-themes/commits/master

https://github.com/excaliburjs/excaliburjs.github.io/blob/site/docs.js#L20

https://travis-ci.org/excaliburjs/excaliburjs.github.io/builds/181169848

Now, I could just fix this solely in my fork--but I think it's best if npm install just worked cross-platform anyway to benefit contributors or use cases like mine.
