### ISSUE TITLE
Possible erroneous class name

### ISSUE THREAD

**Issue by kgryte** [TypeStrong/typedoc-default-themes#62]
Is the class name `tsd-parameter-siganture` intentional or a bug?

See [here](https://github.com/TypeStrong/typedoc-default-themes/blob/f992ea329904db58671a553c30171eb8fdfd3690/src/default/partials/parameter.hbs#L3) and [here](https://github.com/TypeStrong/typedoc-default-themes/blob/f992ea329904db58671a553c30171eb8fdfd3690/src/default/assets/css/elements/_signatures.sass#L143) for its presence in the code base.

**Comment by Gerrit0** [comment]
Fixed with #93

**Comment by kgryte** [comment]
Thanks!
