### ISSUE TITLE
[Security] vulnerable dependency reported in npm audit

### ISSUE THREAD

**Issue by GangWang01** [TypeStrong/typedoc-default-themes#71]
Hi, for latest typedoc-default-themes 0.6.0-0 that is used by typedoc 0.15.0-0, the vulnerable version of dependency jquery was still reported in npm audit. I noticed there is an existing issue [TypeStrong/typedoc#994](https://github.com/TypeStrong/typedoc/issues/994) to track this and jquery was updated to ^3.3.1. But it looks like it needs higher version >=3.4.0 in my npm audit below. Could you please `npm audit fix` your package and publish to npm?

npm audit output follows:
  Moderate        Prototype Pollution                                           
                                                                                
  Package         jquery                                                        
                                                                                
  Patched in      >=3.4.0                                                       
                                                                                
  Dependency of   typedoc [dev]                                                 
                                                                                
  Path            typedoc > typedoc-default-themes > jquery                     
                                                                                
  More info       https://nodesecurity.io/advisories/796                        
                                                                                
                                                                                
  High            Cross-Site Scripting (XSS)                                    
                                                                                
  Package         jquery                                                        
                                                                                
  Patched in      >=3.0.0                                                       
                                                                                
  Dependency of   typedoc [dev]                                                 
                                                                                
  Path            typedoc > typedoc-default-themes > jquery                     
                                                                                
  More info       https://nodesecurity.io/advisories/328

**Comment by Gerrit0** [comment]
This has already been fixed in #70, just hasn't been released yet.

**Comment by GangWang01** [comment]
> This has already been fixed in #70, just hasn't been released yet.

Great! looking forward to the new release of typedoc-default-themes and typedoc both.
