### ISSUE TITLE
When multiple method signatures exist, clicking a link within one does nothing

### ISSUE THREAD

**Issue by alalonde** [TypeStrong/typedoc-default-themes#80]
See for example https://docs.convergence.io/js-api/classes/historicalmodel.html#elementat. Clicking a link within the signature definition should navigate to that link, instead it just toggles the currently visible one.

**Comment by Gerrit0** [comment]
Resolved by #81, I'll leave this open to track the next release

**Comment by Gerrit0** [comment]
Fixed in v0.6.1
