### ISSUE TITLE
Remove jQuery

### ISSUE THREAD

**Issue by BennyHinrichs** [TypeStrong/typedoc-default-themes#85]
I would be willing to go through and remove jQuery from the codebase. Before I do, I just want to know if that would be desired and merged?

**Comment by Gerrit0** [comment]
:+1: I'd definitely be in favor of this, the default theme is really quite simple, it doesn't do very much and includes both jQuery and Lodash in order to do it, which feels at least a bit overkill.

I know @aciccarello was concerned about changing the exposed surface of the `typedoc` global, but I just looked through the most popular themes and none of them added anything on to the existing JS, they either left it as is or replaced it completely.

**Comment by BennyHinrichs** [comment]
Behold: https://github.com/BennyHinrichs/typedoc-default-themes/tree/remove-jquery

It looks we still have to have both jQuery and Underscore in the dependencies because of Backbone?

**Comment by Gerrit0** [comment]
I guess to remove jQuery we'd also have to get rid of Backbone then.

**Comment by BennyHinrichs** [comment]
One way to do that is to simply turn them into custom HTML elements. Probably wouldn't even be that big of a change. A little more code in the component files, plus we could probably get rid of Application.ts entirely. I've never mixed custom elements and TypeScript, so it would be an adventure.

**Comment by sgrishchenko** [comment]
I have read this conversation and I like this idea. I have seen [this fork](https://github.com/BennyHinrichs/typedoc-default-themes/tree/remove-jquery), but I think this is bad idia to rewrite all libriary in one commit. I have tried to work with this problem and found this mistakes: 
- https://github.com/BennyHinrichs/typedoc-default-themes/commit/15eecf2f5e537c64840bac0783567ea26e1b3c39#r37827830
- https://github.com/BennyHinrichs/typedoc-default-themes/commit/15eecf2f5e537c64840bac0783567ea26e1b3c39#r37827856
- https://github.com/BennyHinrichs/typedoc-default-themes/commit/15eecf2f5e537c64840bac0783567ea26e1b3c39#r37827892

So many changes can cause big regression. I think, it will be better to make this changes iterativly. I have tried to make first step in this direction and made this pull request #97. I hope this will help to achive good results.

**Comment by sgrishchenko** [comment]
I have finished all works for query removing. Here list of PRs: #97, #98, #99, #100.
Now js bundle size has reduced from 174 KB to 35 KB (lunr library weighs 29 KB).
Thanks @BennyHinrichs for his work too. I have used some solutions and ideas from his repository.

**Comment by BennyHinrichs** [comment]
Hey, looks pretty good! You took what I did and went the extra mile. That size reduction is awesome :)

**Comment by Gerrit0** [comment]
Thank you both! I should have time to look at the PRs this weekend or next week :)

**Comment by Gerrit0** [comment]
Merged in :) I squashed the commits together to preserve conventional commit style.

Released in 0.9.0, which the next patch of TypeDoc will use.
